version: '3.9'
services:
  eureka1:
    image: eclipse-temurin:17-jre
    container_name: eureka1
    networks:
      - backend
    ports:
      - "8761:8761"
    volumes:
      - ./eureka:/app
    working_dir: /app
    command: ["java", "-jar", "build/libs/eureka-0.0.1-SNAPSHOT.jar"]
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka2:8762/eureka/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/actuator/health"]
      interval: 2s
      timeout: 3s
      retries: 10

  eureka2:
    image: eclipse-temurin:17-jre
    container_name: eureka2
    networks:
      - backend
    ports:
      - "8762:8761"
    volumes:
      - ./eureka:/app
    working_dir: /app
    command: [ "java", "-jar", "build/libs/eureka-0.0.1-SNAPSHOT.jar" ]
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka1:8761/eureka/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/actuator/health"]
      interval: 2s
      timeout: 3s
      retries: 10

  gw:
    image: eclipse-temurin:17-jre
    hostname: gw
    networks:
      - backend
      - frontend
    ports:
      - "28081:8080"
    volumes:
      - ./gw:/app
    working_dir: /app
    command: ["java", "-jar", "build/libs/gw-0.0.1-SNAPSHOT.jar"]
    depends_on:
      eureka1:
        condition: service_healthy
      eureka2:
        condition: service_healthy

  app1:
    image: eclipse-temurin:17-jre
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
      - spring.application.name=app1
      - HOSTNAME={{.Service.Name}}-{{.Task.Slot}}
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["java", "-jar", "build/libs/app-0.0.1-SNAPSHOT.jar"]
    depends_on:
      eureka1:
        condition: service_healthy
      eureka2:
        condition: service_healthy

  app2:
    image: eclipse-temurin:17-jre
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
      - spring.application.name=app2
      - HOSTNAME={{.Service.Name}}-{{.Task.Slot}}
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["java", "-jar", "build/libs/app-0.0.1-SNAPSHOT.jar"]
    depends_on:
      eureka1:
        condition: service_healthy
      eureka2:
        condition: service_healthy

  app3:
    image: eclipse-temurin:17-jre
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
      - spring.application.name=app3
      - HOSTNAME={{.Service.Name}}-{{.Task.Slot}}
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["java", "-jar", "build/libs/app-0.0.1-SNAPSHOT.jar"]
    depends_on:
      eureka1:
        condition: service_healthy
      eureka2:
        condition: service_healthy

networks:
  frontend:
  backend:
