version: '3.8'
services:
  eureka:
    build: ./eureka
    container_name: eureka
    networks:
      - backend
      - frontend
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    volumes:
      - ./eureka:/app
    working_dir: /app
    command: ["java", "-jar", "build/libs/eureka-0.0.1-SNAPSHOT.jar"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 6

  gw:
    image: openjdk:17-jdk-slim
    container_name: gw
    networks:
      - backend
      - frontend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    volumes:
      - ./gw:/app
    working_dir: /app
    command: ["java", "-jar", "build/libs/gw-0.0.1-SNAPSHOT.jar"]
    depends_on:
      eureka:
        condition: service_healthy

  app1:
    image: openjdk:17-jdk-slim
    container_name: app1
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - spring.application.name=app1
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["java", "-jar", "build/libs/app-0.0.1-SNAPSHOT.jar"]
    depends_on:
      eureka:
        condition: service_healthy

  app2:
    image: openjdk:17-jdk-slim
    container_name: app2
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - spring.application.name=app2
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["java", "-jar", "build/libs/app-0.0.1-SNAPSHOT.jar"]
    depends_on:
      eureka:
        condition: service_healthy

  app3:
    image: openjdk:17-jdk-slim
    container_name: app3
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - spring.application.name=app3
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["java", "-jar", "build/libs/app-0.0.1-SNAPSHOT.jar"]
    depends_on:
      eureka:
        condition: service_healthy

networks:
  frontend:
  backend:
