apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-gw-infra.fullname" . }}
  labels:
    app: {{ include "helm-gw-infra.fullname" . }}
    {{ include "helm-gw-infra.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helm-gw-infra.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "helm-gw-infra.fullname" . }}
        release: {{ .Release.Name }}
        {{ include "helm-gw-infra.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ if .Values.serviceAccount.create }}{{ .Values.serviceAccount.name | default (include "helm-gw-infra.fullname" .) }}{{ end }}
      containers:
        - name: {{ .Values.name | default "app" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: {{ .Values.name }}-volume
              mountPath: /app
          workingDir: {{ .Values.workingDir }}
          command: {{ .Values.command }}
          env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      volumes:
        - name: {{ .Values.name }}-volume
          hostPath:
            path: {{ (index .Values.volumes .Values.name).hostPath | default "/default/path" }}
