apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-gw-infra.fullname" . }}
  labels:
    {{ include "helm-gw-infra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "helm-gw-infra.fullname" . }}
