server:
  port: 8082
  servlet.context-path: /
spring.application.name: app0
eureka.client.enabled: false

jackson.serialization.indent_output: true

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always