server:
  port: 0
  servlet.context-path: /${spring.application.name}

jackson.serialization.indent_output: true

management:
  endpoints:
    web.exposure.include: health, info, env, configprops, loggers, metrics
    enabled-by-default: true
  endpoint.health.show-details: always

eureka.client.service-url.defaultZone: http://eureka:8761/eureka/eureka/
