server:
  port: 0
  servlet.context-path: /${spring.application.name}

spring.application.instance-id: ${HOSTNAME}:${spring.application.name}:${server.port}

eureka.client:
  enabled: true
  service-url.defaultZone: http://eureka1:8761/eureka/eureka/,http://eureka2:8762/eureka/eureka/
